### PR TITLE
New DSL for policy jars management

### PR DESCRIPTION
**Pull request by sgomezg**
#### Description
We will use a small DSL to parse some extra data from policies

#### Reviewer
@danielcsant   

#### Test
No changes

#### Coverage
No changes

#### Scalastyle
No info

### CODE REVIEW

**Comment by gserranojc** [comment]
This PR afect my PR, because I make the jars plugins and driver treatment, I make the correct sparktaClusterJob and upload the jobs with spark-submit.

I cancel it, then we can disscuss where the config of spakta must be.

**Comment by sgomezg** [comment]
Ok, but they aren't incompatibles. Please finish yours and I'll make te merge. Thanks :)

**Comment by gserranojc** [comment]
See your PR, is the same, only one var that is not used.

Please cancel it.

**Comment by sgomezg** [comment]
I used a [DSL](https://en.wikipedia.org/wiki/Domain-specific_language) to make more easy JAR management, Is similar but I think is better approach. Please, have a look to the PR and let me know if you have any comments. About the var, I'll remove it, thanks.

**Comment by sgomezg** [comment]
Discussed offline. For better times :-)

**Pull request closed without merging**
