### PR TITLE
Test aceptation for filters and bug corrected

### PR DESCRIPTION
**Pull request by gserranojc**
#### Description

* Bug in FilterModel extraction corrected.
* Test in test-at for filters adapted to twitter example.

#### Reviewer
@anistal

### CODE REVIEW

**Comment by sgomezg** [comment]
LGTM +1

**Comment by gserranojc** [comment]
I need one more commit, don't merge this PR now!

**Comment by sgomezg** [comment]
If you're modifying current PR, please let me know when you're finished. I'll review it again at that time.

**Comment by gserranojc** [comment]
All are corrected. You can see the last commit.

**Comment by anistal** [comment]
+1

**Pull request merged**
