### PR TITLE
SPARKTA-139 Policy actors seem to not be dying

### PR DESCRIPTION
**Pull request by danielcsant**
#### Description
Removed actor when deleting the policy

#### Reviewer
@sgomezg 

#### Test
All passed.

#### Coverage
No changes

#### Scalastyle
No info

### CODE REVIEW

**Comment by sgomezg** [comment]
Test-at pom points to 0.7.0-RC2-SNAPSNOT instead of RC3. The rest of changes, LGTM :)

**Comment by danielcsant** [comment]
done! thanks

**Comment by gserranojc** [comment]
This not correct when the actors are not been killed in the Actor.system

**Comment by danielcsant** [comment]
Done

**Comment by sgomezg** [comment]
+1

**Comment by gserranojc** [comment]
+1

**Pull request merged**
