### PR TITLE
Policies auto-versioned in Zookeeper for Outputs tables names

### PR DESCRIPTION
**Pull request by gserranojc**
#### Description

Now all the policies are versioned in Zookeeper. When the user modify one cube that contains the policy we increment the version number.

Cassandra output are refactored, now use the policy version for the names of the tables associated to one cube.
 
#### Reviewer

@sgomezg  @anistal @arinconstrio

### CODE REVIEW

**Comment by arinconstrio** [comment]
It seems works, but do we want have this behaviour ONLY with C*?

**Comment by sgomezg** [comment]
Agree with @arinconstrio. Moreover, if version is optional and you only want to use it in C*, maybe you can place it as last parameter and initialize it to None.

**Comment by gserranojc** [comment]
I think that probably we must use it by default in ElasticSearch, because if we don't want to make one re-Index process: https://www.elastic.co/blog/changing-mapping-with-zero-downtime
In Solr is the same. 
In Mongo we must make one process for remake the indexes if are different or use this utility.

What do you think guys??
We resolve this problems in others PR's?? This PR is related to the Cassandra issue..

**Comment by sgomezg** [comment]
Works for me.

**Comment by arinconstrio** [comment]
If you think that ElasticSearch and others are out of scope of this PR, pls open the related Jira issues

**Comment by gserranojc** [comment]
Ok!! I will open the issues for ElasticSearch and MongoDB.

**Pull request merged**
