### PR TITLE
Support to Spark 1.4.1 and 1.5.2

### PR DESCRIPTION
**Pull request by sgomezg**
#### Description
Changes to be compatible with multiple Spark versions using profiles. SPARKTA-207

#### Reviewer
@gserranojc, @danielcsant    

#### Test
All passed.

#### Coverage
No changes

#### Scalastyle
No info

### CODE REVIEW

**Comment by gserranojc** [comment]
+1

**Comment by danielcsant** [comment]
Please edit the documentation:
https://stratio.atlassian.net/wiki/display/SPARKTA0x8

**Comment by sgomezg** [comment]
https://stratio.atlassian.net/wiki/display/SPARKTA0x8/15.+Building+Sparkta

**Comment by gserranojc** [comment]
+1

**Comment by danielcsant** [comment]
+1

**Pull request merged**
