### PR TITLE
Refactor on complete in spray-routing. Now, it returns future.

### PR DESCRIPTION
**Pull request by dvallejo**
#### Description
- Changed Await.result to Future. Now, spray returns Future.
- Changed validation block to if sentence with BadRequest response.

#### Test
All passed

#### Coverage
No changes

#### Scalastyle
No info

### CODE REVIEW

**Comment by arinconstrio** [comment]
Why don't you implement  PolicyHelper in the same way?

 val future = actor ? new FindByTypeAndId(fragment.fragmentType, fragment.id.get)
      Await.result(future, timeout.duration) match {
        case ResponseFragment(Failure(exception)) => throw exception
        case ResponseFragment(Success(fragment)) => fragment
      }

**Comment by dvallejo** [comment]
I hadn' t seen this block of code. I'm going to refactor too. Thanks!

**Comment by dvallejo** [comment]
Done. 
I've refactored the method called fillFragments. In order to continue working with Futures, I had to do some changes in the methods that call this method.
There are many changes because the auto-indent of the IDE. So, there are some changes about removing or adding white spaces.

**Comment by arinconstrio** [comment]
policyContext endpoint doesn't answer (at least) on time

2015-09-10 17:27:25,896 (sparkta-akka.actor.default-dispatcher-2) [INFO - com.stratio.sparkta.serving.core.policy.status.PolicyStatusActor.update(PolicyStatusActor.scala:45)] >> Updating context 1cebbeaf-51ab-453c-8226-147d466d5627 : <Launched> to <Starting>
2015-09-10 17:27:40,781 (sparkta-akka.actor.default-dispatcher-8) [ERROR - com.stratio.sparkta.serving.api.actor.ControllerActor$$anonfun$exceptionHandler$1$$anonfun$applyOrElse$2.apply(ControllerActor.scala:50)] Ask timed out on [Actor[akka://sparkta/user/sparkStreamingContextActor#119620174]] after [15000 ms]
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://sparkta/user/sparkStreamingContextActor#119620174]] after [15000 ms]

curl -X POST -H "Content-Type: application/json" --data @examples/policies/fragments/IWebSocket-OPrint.json  localhost:9090/policyContext
{"i18nCode":"666","message":"Ask timed out on [Actor[akka://sparkta/user/sparkStreamingContextActor#119620174]] after [15000 ms]"}

**Comment by dvallejo** [comment]
I've updated my branch with the last changes of master. Now, it fails in my local copy too.
I've fixed the bug in the last commit.

**Pull request merged**
