### PR TITLE
Spark submit with all yarn params

### PR DESCRIPTION
**Pull request by sgomezg**
#### Description
Spark submit with all yarn params. This PR must be merged after #625 because it includes these changes

#### Reviewer
@anistal    

#### Test
No changes

#### Coverage
No changes

#### Scalastyle
No info

### CODE REVIEW

**Comment by gserranojc** [comment]
This PR afect my PR, because I make the jars plugins and driver treatment, I make the correct sparktaClusterJob and upload the jobs with spark-submit.

Pease cancel it.

**Comment by sgomezg** [comment]
Ok, but they aren't incompatibles. Please finish yours and I'll make te merge.  Tnanks :)

**Comment by gserranojc** [comment]
You must probe yarn in cluster mode, the params and the spark-submit only use it for test, don't submit this changes.

**Comment by sgomezg** [comment]
Discussed offline.

**Pull request closed without merging**
