### PR TITLE
SPARKTA-225 Reduced packaging time in zinc profile

### PR DESCRIPTION
**Pull request by danielcsant**
#### Description
Removed license plugin in zinc profile

#### Reviewer
@sgomezg     

#### Test
All OK
#### Coverage
No changes

#### Scalastyle
No info

### CODE REVIEW

**Comment by gserranojc** [comment]
+1

**Comment by sgomezg** [comment]
This config is invalid. We need scala plugin as default.

**Comment by danielcsant** [comment]
scala plugin is taken from parent as default

`<groupId>com.stratio</groupId>`
`<artifactId>parent</artifactId>`
`<version>0.5.0</version>`

**Comment by danielcsant** [comment]
Done! thanks

**Comment by sgomezg** [comment]
LGTM :)

**Pull request merged**
